estateTaxes="•	Through 2009,"
estateTaxes+="\n	the same rate " 
estateTaxes+="\n	schedule is used " 
estateTaxes+="\n	for gifts and " 
estateTaxes+="\n	estates " 
estateTaxes+="\n•	Gifts and final "
estateTaxes+="\n	estate assets" 
estateTaxes+="\n	are aggregated "
estateTaxes+="\n	to determine tax "
estateTaxes+="\n•	Maximum " 
estateTaxes+="\n	scheduled rate " 
estateTaxes+="\n	for 2009 is 45%" 


giftTaxes="•	Only the credit is used "
giftTaxes+="\n	in the actual tax" 
giftTaxes+="\n	calculation"
giftTaxes+="\n•	Exclusion amount" 
giftTaxes+="\n	illustrates the value" 
giftTaxes+="\n	offset by the credit "
giftTaxes+="\n•	Estate exclusion  " 
giftTaxes+="\n	amount = $3,500,000" 
giftTaxes+="\n	for year 2009"
giftTaxes+="\n•	Exclusion amount for" 
giftTaxes+="\n	gifts remains at" 
giftTaxes+="\n	$1,000,000 for 2009"
giftTaxes+="\n	and 2010."

giftTaxes+="\n•	First taxable dollar in" 
giftTaxes+="\n	estates of persons" 
giftTaxes+="\n	dying in 2009 is"
giftTaxes+="\n	at the 45% rate"

deductions="•	Deductions are taken" 
deductions+="\n	<b>before</b> the tax is"
deductions+="\n	calculated"
deductions+="\n•	The amount that can "
deductions+="\n	be transferred between"
deductions+="\n	spouses without tax"
deductions+="\n	is generally <b>unlimited</b>" 
deductions+="\n•	Transfers to Charities" 
deductions+="\n	are not taxed" 

