estateTaxes="•	The same rate"
estateTaxes+="\n	schedule is used" 
estateTaxes+="\n	for gifts and" 
estateTaxes+="\n	estates" 
estateTaxes+="\n•	Taxable gifts and "
estateTaxes+="\n	final estate assets" 
estateTaxes+="\n	are aggregated "
estateTaxes+="\n	to determine tax "
estateTaxes+="\n•	Maximum " 
estateTaxes+="\n	scheduled rate " 
estateTaxes+="\n	for 2011 is 35%" 


giftTaxes="•	Only the Credit is used "
giftTaxes+="\n	in the actual tax" 
giftTaxes+="\n	calculation"
giftTaxes+="\n•	Exclusion Amount"  
giftTaxes+="\n	illustrates the value" 
giftTaxes+="\n	offset by the credit" 
giftTaxes+="\n•	Applicable Exclusion" 
giftTaxes+="\n	Amount for estates and" 
giftTaxes+="\n	gifts = $5,000,000 for"
giftTaxes+="\n	year 2011"
giftTaxes+="\n•	Prior to 2011, the" 
giftTaxes+="\n	portion of the" 
giftTaxes+="\n	Applicable Exclusion "
giftTaxes+="\n	Amount that could be "
giftTaxes+="\n	used for lifetime gifts  "
giftTaxes+="\n	could not exceed"
giftTaxes+="\n	$1,000,000"

giftTaxes+="\n•	First taxable dollar in" 
giftTaxes+="\n	estates of persons" 
giftTaxes+="\n	dying in 2011 for which"
giftTaxes+="\n	a tax will actually be"
giftTaxes+="\n	paid is at the 35% "
giftTaxes+="\n	rate (i.e. everything"
giftTaxes+="\n	over the Applicable"
giftTaxes+="\n	Exclusion Amount is"
giftTaxes+="\n	taxed at 35%)"
giftTaxes+="\n•	Portability of the"
giftTaxes+="\n	Applicable Exclusion"
giftTaxes+="\n	Amount is available to"
giftTaxes+="\n	spouses in 2011 and"
giftTaxes+="\n	2012"


deductions="•	Deductions are taken" 
deductions+="\n	<b>before</b> the tax is"
deductions+="\n	calculated"
deductions+="\n•	The amount that can "
deductions+="\n	be transferred between"
deductions+="\n	spouses without tax"
deductions+="\n	is generally <b>unlimited</b>" 
deductions+="\n•	Transfers to Charities" 
deductions+="\n	are not taxed" 

